mkdir CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP

cp archive.sh CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP/
cp Doxyfile CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP/
cp -r headers/ CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP/
cp -r html/ CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP/
cp Install_FastCGI.md CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP/
cp -r libparser/ CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP/
cp librequest-0.5 CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP/
cp README.md CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP/
cp -r src/ CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP/

tar -cvzf CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP.tgz CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP/

rm -Rf CHOGNOT_ARNAUD_DACOSTA_ProjetHTTP/